//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMethod {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FactoryMethodResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FactoryMethodResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FactoryMethod.FactoryMethodResources", typeof(FactoryMethodResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This skill means, that this employee has good verbal and non-verbal communication skills..
        /// </summary>
        internal static string CommunicationSkillDescription {
            get {
                return ResourceManager.GetString("CommunicationSkillDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This skill means, that this employee can adapt easily to new circumstances and environments..
        /// </summary>
        internal static string FlexibilitySkillDescription {
            get {
                return ResourceManager.GetString("FlexibilitySkillDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This skill means, that this employee is able to organise his workload and plan his daily task effectively..
        /// </summary>
        internal static string PlanningSkillDescription {
            get {
                return ResourceManager.GetString("PlanningSkillDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This skill means, that this employee is able to use his own initiative to prioritise his task, come up with better ways of working and take responsibility of his own projects..
        /// </summary>
        internal static string SelfMotivationSkillDescription {
            get {
                return ResourceManager.GetString("SelfMotivationSkillDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This skill means, that this employee can perfectly fit a team and work closely with other team members..
        /// </summary>
        internal static string TeamworkSkillDescription {
            get {
                return ResourceManager.GetString("TeamworkSkillDescription", resourceCulture);
            }
        }
    }
}
